{% set name = "napari-script-editor" %}
{% set version = "0.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-script-editor-{{ version }}.tar.gz
  sha256: c89dd6032f7571b549f23fc98ff3b393085c096a966fffebcaade0931de28398

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - haesleinhuepf-pyqode.core >=2.15.5
    - haesleinhuepf-pyqode.python >=2.15.2
    - jedi >=0.18.0
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >=3.7
    - pyflakes <=2.4.0
    - imageio !=2.22.1

test:
  imports:
    - napari_script_editor
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-script-editor
  summary: A python script editor for napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
